-- Hyderabad tech companies
INSERT INTO companies (name, description, address, location, sector, area, city, founded_year, team_size, total_funding, stage, status, website_url, linkedin_url, logo_url)
VALUES
    -- HITEC City
    ('TCS Hyderabad', 'IT consulting and digital transformation.', 'HITEC City, Hyderabad', ST_SetSRID(ST_MakePoint(78.3815, 17.4435), 4326), 'Other', 'HITEC City', 'Hyderabad', 1968, '10000+', 'Public', 'Public', 'active', 'https://tcs.com', 'https://linkedin.com/company/tcs', 'https://www.google.com/s2/favicons?domain=tcs.com'),
    ('Infosys Hyderabad', 'IT consulting and software development.', 'HITEC City, Hyderabad', ST_SetSRID(ST_MakePoint(78.3820, 17.4440), 4326), 'Other', 'HITEC City', 'Hyderabad', 1981, '10000+', 'Public', 'Public', 'active', 'https://infosys.com', 'https://linkedin.com/company/infosys', 'https://www.google.com/s2/favicons?domain=infosys.com'),
    ('Wipro Hyderabad', 'IT services and digital transformation.', 'HITEC City, Hyderabad', ST_SetSRID(ST_MakePoint(78.3825, 17.4445), 4326), 'Other', 'HITEC City', 'Hyderabad', 1945, '10000+', 'Public', 'Public', 'active', 'https://wipro.com', 'https://linkedin.com/company/wipro', 'https://www.google.com/s2/favicons?domain=wipro.com'),
    ('Cognizant Hyderabad', 'Digital transformation consulting.', 'HITEC City, Hyderabad', ST_SetSRID(ST_MakePoint(78.3830, 17.4450), 4326), 'Other', 'HITEC City', 'Hyderabad', 1994, '10000+', 'Public', 'Public', 'active', 'https://cognizant.com', 'https://linkedin.com/company/cognizant', 'https://www.google.com/s2/favicons?domain=cognizant.com'),
    ('Deloitte Hyderabad', 'Professional services and consulting.', 'HITEC City, Hyderabad', ST_SetSRID(ST_MakePoint(78.3805, 17.4430), 4326), 'Other', 'HITEC City', 'Hyderabad', 1845, '10000+', 'Public', 'Public', 'active', 'https://deloitte.com', 'https://linkedin.com/company/deloitte', 'https://www.google.com/s2/favicons?domain=deloitte.com'),
    ('Capgemini Hyderabad', 'IT consulting and digital services.', 'HITEC City, Hyderabad', ST_SetSRID(ST_MakePoint(78.3810, 17.4425), 4326), 'Other', 'HITEC City', 'Hyderabad', 1967, '10000+', 'Public', 'Public', 'active', 'https://capgemini.com', 'https://linkedin.com/company/capgemini', 'https://www.google.com/s2/favicons?domain=capgemini.com'),
    ('Accenture Hyderabad', 'Technology consulting and services.', 'HITEC City, Hyderabad', ST_SetSRID(ST_MakePoint(78.3800, 17.4420), 4326), 'Other', 'HITEC City', 'Hyderabad', 1989, '10000+', 'Public', 'Public', 'active', 'https://accenture.com', 'https://linkedin.com/company/accenture', 'https://www.google.com/s2/favicons?domain=accenture.com'),
    -- Gachibowli
    ('Amazon Hyderabad', 'E-commerce, cloud computing (AWS).', 'Gachibowli, Hyderabad', ST_SetSRID(ST_MakePoint(78.3500, 17.4200), 4326), 'Consumer', 'Gachibowli', 'Hyderabad', 2005, '10000+', 'Public', 'Public', 'active', 'https://amazon.in', 'https://linkedin.com/company/amazon', 'https://www.google.com/s2/favicons?domain=amazon.in'),
    ('Microsoft Hyderabad', 'Productivity software, Azure cloud.', 'Gachibowli, Hyderabad', ST_SetSRID(ST_MakePoint(78.3510, 17.4210), 4326), 'SaaS', 'Gachibowli', 'Hyderabad', 2001, '5000+', 'Public', 'Public', 'active', 'https://microsoft.com', 'https://linkedin.com/company/microsoft', 'https://www.google.com/s2/favicons?domain=microsoft.com'),
    ('Google Hyderabad', 'Search, cloud, AI/ML technology.', 'Gachibowli, Hyderabad', ST_SetSRID(ST_MakePoint(78.3520, 17.4220), 4326), 'AI', 'Gachibowli', 'Hyderabad', 2004, '5000+', 'Public', 'Public', 'active', 'https://google.com', 'https://linkedin.com/company/google', 'https://www.google.com/s2/favicons?domain=google.com'),
    ('Facebook Hyderabad', 'Social media and technology platform.', 'Gachibowli, Hyderabad', ST_SetSRID(ST_MakePoint(78.3530, 17.4230), 4326), 'AI', 'Gachibowli', 'Hyderabad', 2010, '5000+', 'Public', 'Public', 'active', 'https://meta.com', 'https://linkedin.com/company/meta', 'https://www.google.com/s2/favicons?domain=meta.com'),
    ('Uber Hyderabad', 'Ride-hailing technology platform.', 'Gachibowli, Hyderabad', ST_SetSRID(ST_MakePoint(78.3540, 17.4240), 4326), 'Consumer', 'Gachibowli', 'Hyderabad', 2013, '500+', 'Public', 'Public', 'active', 'https://uber.com', 'https://linkedin.com/company/uber', 'https://www.google.com/s2/favicons?domain=uber.com'),
    ('Salesforce Hyderabad', 'Cloud-based CRM and enterprise software.', 'Gachibowli, Hyderabad', ST_SetSRID(ST_MakePoint(78.3550, 17.4250), 4326), 'SaaS', 'Gachibowli', 'Hyderabad', 2005, '5000+', 'Public', 'Public', 'active', 'https://salesforce.com', 'https://linkedin.com/company/salesforce', 'https://www.google.com/s2/favicons?domain=salesforce.com'),
    ('Oracle Hyderabad', 'Enterprise software, cloud infrastructure.', 'Gachibowli, Hyderabad', ST_SetSRID(ST_MakePoint(78.3560, 17.4260), 4326), 'SaaS', 'Gachibowli', 'Hyderabad', 1997, '5000+', 'Public', 'Public', 'active', 'https://oracle.com', 'https://linkedin.com/company/oracle', 'https://www.google.com/s2/favicons?domain=oracle.com'),
    ('SAP Hyderabad', 'Enterprise software and cloud solutions.', 'Gachibowli, Hyderabad', ST_SetSRID(ST_MakePoint(78.3570, 17.4270), 4326), 'SaaS', 'Gachibowli', 'Hyderabad', 1998, '5000+', 'Public', 'Public', 'active', 'https://sap.com', 'https://linkedin.com/company/sap', 'https://www.google.com/s2/favicons?domain=sap.com'),
    -- Madhapur
    ('Paytm Hyderabad', 'Digital payments platform.', 'Madhapur, Hyderabad', ST_SetSRID(ST_MakePoint(78.3900, 17.4500), 4326), 'Fintech', 'Madhapur', 'Hyderabad', 2015, '500+', '$3.5B', 'Growth', 'active', 'https://paytm.com', 'https://linkedin.com/company/paytm', 'https://www.google.com/s2/favicons?domain=paytm.com'),
    ('Flipkart Hyderabad', 'E-commerce marketplace.', 'Madhapur, Hyderabad', ST_SetSRID(ST_MakePoint(78.3910, 17.4510), 4326), 'Consumer', 'Madhapur', 'Hyderabad', 2007, '10000+', 'Walmart', 'Public', 'active', 'https://flipkart.com', 'https://linkedin.com/company/flipkart', 'https://www.google.com/s2/favicons?domain=flipkart.com'),
    ('Ola Hyderabad', 'Ride-hailing and EV platform.', 'Madhapur, Hyderabad', ST_SetSRID(ST_MakePoint(78.3920, 17.4520), 4326), 'Consumer', 'Madhapur', 'Hyderabad', 2010, '5000+', '$4.5B', 'Growth', 'active', 'https://olacabs.com', 'https://linkedin.com/company/ola', 'https://www.google.com/s2/favicons?domain=olacabs.com'),
    ('Zoho Hyderabad', 'Cloud-based business software suite.', 'Madhapur, Hyderabad', ST_SetSRID(ST_MakePoint(78.3930, 17.4530), 4326), 'SaaS', 'Madhapur', 'Hyderabad', 1996, '10000+', 'Bootstrapped', 'Growth', 'active', 'https://zoho.com', 'https://linkedin.com/company/zoho', 'https://www.google.com/s2/favicons?domain=zoho.com'),
    -- Financial District
    ('Visa Hyderabad', 'Digital payments technology.', 'Financial District, Hyderabad', ST_SetSRID(ST_MakePoint(78.3400, 17.4100), 4326), 'Fintech', 'Financial District', 'Hyderabad', 2007, '10000+', 'Public', 'Public', 'active', 'https://visa.com', 'https://linkedin.com/company/visa', 'https://www.google.com/s2/favicons?domain=visa.com'),
    ('HSBC Hyderabad', 'Banking and financial services technology.', 'Financial District, Hyderabad', ST_SetSRID(ST_MakePoint(78.3410, 17.4110), 4326), 'Fintech', 'Financial District', 'Hyderabad', 1998, '5000+', 'Public', 'Public', 'active', 'https://hsbc.com', 'https://linkedin.com/company/hsbc', 'https://www.google.com/s2/favicons?domain=hsbc.com'),
    ('Barclays Hyderabad', 'Banking technology and analytics.', 'Financial District, Hyderabad', ST_SetSRID(ST_MakePoint(78.3420, 17.4120), 4326), 'Fintech', 'Financial District', 'Hyderabad', 2000, '5000+', 'Public', 'Public', 'active', 'https://barclays.com', 'https://linkedin.com/company/barclays', 'https://www.google.com/s2/favicons?domain=barclays.com'),
    ('JPMorgan Hyderabad', 'Financial services and technology.', 'Financial District, Hyderabad', ST_SetSRID(ST_MakePoint(78.3430, 17.4130), 4326), 'Fintech', 'Financial District', 'Hyderabad', 2005, '5000+', 'Public', 'Public', 'active', 'https://jpmorgan.com', 'https://linkedin.com/company/jpmorgan', 'https://www.google.com/s2/favicons?domain=jpmorgan.com')
ON CONFLICT (name) DO NOTHING;
